server:
  port: 8080

spring:
  mvc:
    pathmatch:
      # 引入swagger3.0时加入的配置 localhost:8080/doc.html
      matching-strategy: ant_path_matcher
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      # p6spy: true
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: mysql
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        mysql:
          driverClassName: com.mysql.cj.jdbc.Driver
          # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
          # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowMultiQueries=true
          username: root
          password: 'Abc@1234'
        # 从库数据源
#        clickhouse:
#          lazy: true
#          driverClassName: ru.yandex.clickhouse.ClickHouseDriver
#          url: jdbc:clickhouse://localhost:8123/idc_resource?useSSL=false&allowMultiQueries=true&socket_timeout=600000
#          username: default
#          password: Abc@1234
      hikari:
        # 最大连接池数量
        maxPoolSize: 5
        # 最小空闲线程数量
        minIdle: 2
        # 配置获取连接等待超时的时间
        connectionTimeout: 30000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 600000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        maxLifetime: 1800000
        # 连接测试query（配置检测连接是否有效）
        connectionTestQuery: SELECT 1
        # 多久检查一次连接的活性
        keepaliveTime: 30000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper目录位置
  mapper-locations: classpath:**/mapper/*.xml
